apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ticketing
deploy:
  kubectl:
    remoteManifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: gonjila/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*"
            dest: .
manifests:
  rawYaml:
    - infra/k8s/*
